version: '3.8'
services:
  app:
    build: .
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    environment:
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - SERVER_PORT=${SERVER_PORT}
    depends_on:
      - db
    entrypoint: ["sh", "-c", "while ! nc -z db 3306; do sleep 1; done; java -jar app.jar"]
    networks:
      - app-network

  db:
    image: mysql:8.4
    container_name: football_manager_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "3307:3306"
    networks:
      - app-network

networks:
  app-network:
